services:
  backend:
    image: shlee74/citation-backend:ver01
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
  frontend:
    image: shlee74/citation-frontend:ver01
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend